# Generated by Django 5.2.1 on 2025-05-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblinks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblink',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joblink',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joblink',
            name='pay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
